### ISSUE TITLE
[fix] Refactor current_goal_state

### ISSUE THREAD

**Issue by adrianvrj** [web3wagers/gostarkme#142] opened 2024-10-24 01:27 UTC
### This issue will be part of ODHack9.0, please apply via Onlydust app
- Remove all the logic for the ```current_goal_state```.
- Use the ```dispatcher.balance_of(get_contract_address())``` method instead of ```current_goal_state```.
- Test this implementation.
- Please read [contributors guide](https://github.com/web3wagers/gostarkme/blob/dev/CONTRIBUTORS_GUIDE.md) before asking for an issue

### Acceptance Criteria
- ```current_goal_state``` no longer in any contract.
- ```dispatcher.balance_of(get_contract_address())``` is being used to get the contract balance.
- Tests modified or added.
- All tests passing.

**Comment by raizo07** [comment] 2024-10-24 03:45
Hey @adrianvrj I'll like to assigned to work on this

**Comment by martinvibes** [comment] 2024-10-24 05:37
hello @adrianvrj i'm an experienced frontend developer and a blockchain developer i would love to work on this issue 
Pleasee kindly assign :)

**Comment by derianrddev** [comment] 2024-10-24 07:07
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/go-stark-me).

### My background and how it can be leveraged

Hello, I'm Derian, a software engineer focused on full-stack web development, and I’m currently part of Dojo Coding. I've been studying Cairo through the Starknet Bootcamp, completed all the Starklings exercises, and have been practicing on Node Guardians. I’d like to work on issue #142 and gain more experience. It would be an honor if this were my first issue on OnlyDust. I would really appreciate the opportunity to contribute and be part of this project!

I estimate this will take 2 to 3 days to complete.

### How I plan on tackling this issue
I will study the codebase to understand the current structure and functionality.
I will thoroughly read the issue description to understand the problem that needs to be solved.
I will leverage all provided resources within the issue to get a better grasp of the task.
I will implement the code changes and run the tests in Cairo.
If I have any doubts, I will ask questions as soon as possible in the Discord group.
I will open a PR and make sure the CI tests pass.
I will make the necessary changes based on the PR review.

**Comment by Lukman-01** [comment] 2024-10-24 07:28
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/go-stark-me).

### My background and how it can be leveraged
Hello! My name is Lukman, and I am a passionate Smart Contract Developer with two years of experience in writing smart contracts. My hands-on experience spans various blockchain platforms, including Ethereum and Starknet.

### How I plan on tackling this issue
To tackle this issue, I will begin by identifying all instances of current_goal_state across the relevant contracts and remove any related logic to ensure it is no longer in use. Then, I will implement the dispatcher.balance_of(get_contract_address()) method to retrieve the contract balance, ensuring it replaces all previous usages of current_goal_state. Finally, I will update the existing tests or create new ones to verify the correct functionality of the new implementation, ensuring that all tests pass successfully.

**Comment by sanieni6** [comment] 2024-10-24 07:28
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/go-stark-me).

### My background and how it can be leveraged
Hi there, I am Luis a full-stack dev, i think i can be useful for this task.

### How I plan on tackling this issue
In the file contracts/src/fund.cairo i am going firsly to remove all the current_goal_state logic.
Then i am going to implement the new dispatcher to any place where i remove the old logic.
Finally i am going to ensure that all the tests passed!!

This is my first approach after make a quick check of your contract, however it can be more changes related 
this issue.Let's rock!!

**Comment by SoarinSkySagar** [comment] 2024-10-24 07:49
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/go-stark-me).

### My background and how it can be leveraged
GM @adrianvrj, I am Sagar Rana, a smart contract developer and full stack engineer. I have 3 years of experience building robust full stack applications and over a year of writing smart contracts. You can see my projects and contributions to some major repos on my GitHub profile. The tech stack I use mainly includes Solidity, Rust, Cairo and Typescript. I am also contributing to the Starknet and Rust ecosystems and building on Cairo and Rust languages. I am interested in contributing to projects like this to learn more about these technologies and help make these projects better. Please assign me as I would be really glad to be a contributor in this project! :)

### How I plan on tackling this issue
 - Remove the `current_goal_state: u256` field from Storage struct in `contracts/src/fund.cairo`
 - Remove the `self.current_goal_state.write(FundConstants::INITIAL_GOAL);` from the constructor function
 - Remove the `getCurrentGoalState

**Comment by saimeunt** [comment] 2024-10-24 09:15
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/go-stark-me).

### My background and how it can be leveraged
I have contributed to several Cairo projects on OnlyDust and I've worked on similar issues in the past.

### How I plan on tackling this issue
I will carefully refactor the code as explained in the issue and I'll make sure the tests pass.

**Comment by 0xprivateChaos** [comment] 2024-10-24 11:34
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/go-stark-me).

### My background and how it can be leveraged
I bring 2 years of hands-on experience in writing and optimizing tests for Solidity smart contracts, which has given me strong foundation in blockchain testing patterns. Recently, I've expanded my expertise into Cairo development, actively writing contracts and their corresponding tests. My combination of established testing experience in Solidity and fresh perspective in Cairo, along with deep theoretical knowledge, positions me well to tackle this testing challenge effectively.

### How I plan on tackling this issue
To refactor the ```current_goal_state```, remove all instances where ```current_goal_state``` is read or written in the contract. Replace it by directly checking the contract's token balance using ```dispatcher.balance_of(get_contract_address())```. This way, the balance represents the current state of donations. Update donation-related logic and tests to reflect this balance check instead of  ```current_goal_state```

**Comment by aniruddhaaps** [comment] 2024-10-24 12:24
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/go-stark-me).

### My background and how it can be leveraged
I am a typescript dev. A new-comer here, willing and ready to contribute to contribute to solve the issue

**Comment by jsandinoDev** [comment] 2024-10-24 14:16
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/go-stark-me).

### My background and how it can be leveraged
I'm a full-stack developer with web3 experience member of Dojo Coding, specializing in smart contracts and decentralized applications. I've worked on projects using React, Solidity, Cairo, and blockchain tools. My skills in both front-end and back-end development allow me to build scalable and secure solutions for web3 ecosystems.

### How I plan on tackling this issue
1. Remove All current_goal_state Logic
Search the entire codebase to identify where current_goal_state is being used.
Remove any logic, variables, or references related to current_goal_state from the contract.
Ensure the removal doesn't impact the contract's core functionality in other areas.
2. Implement dispatcher.balance_of
Replace the current_goal_state logic with a call to dispatcher.balance_of(get_contract_address()). This method will retrieve the balance directly from the contract.
Ensure that get_contract_address() is a method or function that correctly retrieves the current contract's address. If it's not already available, create a way to fetch the contract address.
Confirm that dispatcher is properly integrated and available in the contract for use.
3. Update Tests
Modify the existing tests that previously relied on current_goal_state to now check the contract's balance using dispatcher.balance_of.
Ensure tests accurately validate that the new balance-checking logic works as intended.
Add any new test cases required to handle balance retrieval scenarios to ensure full test coverage.
4. Run and Validate Tests
Run the test suite to confirm that all tests pass and the functionality remains intact after the changes.
Check that no part of the contract still references current_goal_state and that dispatcher.balance_of is being used correctly throughout.
Following these steps ensures a smooth transition from current_goal_state logic to using dispatcher.balance_of, and guarantees that the contract’s functionality remains consistent and all tests pass.

**Comment by ryzen-xp** [comment] 2024-10-24 15:36
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/go-stark-me).

### My background and how it can be leveraged
I specialize in blockchain development with experience in Solidity, Cairo, and Rust. I’ve worked on projects involving multi-token support and refactoring contract logic.

### How I plan on tackling this issue
[1]=>Identify and remove all occurrences of current_goal_state in the code.
[2]=>Replace its logic with dispatcher.balance_of(get_contract_address()) to handle contract balances.
[3]=>Update and write tests to ensure the new implementation works as expected.
[4]=>Run all tests and ensure they pass, confirming the successful refactor.
I will ensure smooth integration and efficient performance without breaking existing functionality.

**Closed** 2024-10-30 02:38 UTC
Labels: bug, ODHack9
